# Dockerfile Doc: https://docs.docker.com/engine/reference/builder/
# using python 3.9 docker image
FROM python:3.9

# letting docker know the port
EXPOSE 8080

# setting working directory
WORKDIR /app

# installing pip's requirements file
COPY requirements/ /app/requirements
RUN pip install --upgrade pip
RUN pip install -r ./requirements/dev.txt --no-cache-dir

# copying the api and it's access point
COPY api/ /app/api
COPY entry_point.py /app/entry_point.py

# runing the app
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8080", "--access-log", "--reload"]